# Generated by Django 6.0.4 on 2026-04-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='flatly', max_length=50)),
                ('navbar', models.CharField(default='navbar-white navbar-light', max_length=100)),
                ('sidebar', models.CharField(default='sidebar-light-primary', max_length=100)),
                ('accent', models.CharField(default='accent-primary', max_length=50)),
                ('brand_colour', models.CharField(default='navbar-primary', max_length=50)),
                ('button_primary', models.CharField(default='btn-primary', max_length=50)),
                ('button_secondary', models.CharField(default='btn-secondary', max_length=50)),
                ('button_info', models.CharField(default='btn-info', max_length=50)),
                ('button_warning', models.CharField(default='btn-warning', max_length=50)),
                ('button_danger', models.CharField(default='btn-danger', max_length=50)),
                ('button_success', models.CharField(default='btn-success', max_length=50)),
                ('navbar_fixed', models.BooleanField(default=True)),
                ('sidebar_fixed', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'UI Settings',
                'verbose_name_plural': 'UI Settings',
            },
        ),
    ]
