# python base
FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

# system deps & create virtual env is optional inside docker
RUN apt-get update && apt-get install -y build-essential libpq-dev

COPY ../Pipfile ../Pipfile.lock /app/

RUN pip install pipenv && pipenv install --system --deploy

COPY . /app

# collectstatic
RUN python manage.py collectstatic --noinput

EXPOSE 8000
CMD ["gunicorn", "backend.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3"]
