# Generated by Django 6.0.4 on 2026-04-21 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='imaging.classificationresult')),
            ],
            options={
                'verbose_name': 'Garbage Alert',
                'verbose_name_plural': 'Garbage Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
